### ISSUE TITLE
Intersection of Two Linked Lists II

### ISSUE THREAD

**Issue by Da-Huang** [ziyeqinghan/leetcode#22]
这道题是Intersection of Two Linked Lists的一个升级版，LeetCode上还没有放出来，但我确信肯定迟早会放出来的。

该题在Intersection of Two Linked Lists的基础上允许列表又环。

**Comment by ziyeqinghan** [comment]
看两个是否有环 判断是否是相同的环， 切割环 而后求交点 参见Linked List Cycle II
