### ISSUE TITLE
Divide Two Integers

### ISSUE THREAD

**Issue by Da-Huang** [ziyeqinghan/leetcode#26]
这题不要用long long，否则面试官一定会让你不用long long实现一遍的。

**Comment by ziyeqinghan** [comment]
4/3 = 1, (-4)/3 = -1, (-4)/(-3) = 1, 4/(-3) = -1

4%3 = 1, (-4)%3 = -1, (-4)%(-3) = -1, 4%(-3) = -1

由此可知: 

 1.  | a / b | = | (-a) / b | = | a / (-b) | = | (-a) / (-b) | 由此本题可以转化成除数和被除数都是负数
 2.  (a/b) * b + (a%b) = a
