### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by Da-Huang** [ziyeqinghan/leetcode#28]
此题，我觉得是LeetCode中最难的一道题！

该题最佳解法是O(n)空间，O(n)时间的。

**Comment by Da-Huang** [comment]
请参考[Manacher算法](http://www.felix021.com/blog/read.php?2040)。

**Comment by ziyeqinghan** [comment]
为啥时间是O(n)呢? 不是有可能继续比较的吗？

**Comment by ziyeqinghan** [comment]
j = 2 * id - i
1. mx - i > P[j]  P[i] = P[j]  
2. mx - i < p[j]  p[i] = mx-i 
3. mx - i = p[j] 需要继续比较 s[mx]  并更新id = i , mx的范围扩大 因而每个点最多访问两次。
