### ISSUE TITLE
Unique Binary Search Trees II

### ISSUE THREAD

**Issue by Da-Huang** [ziyeqinghan/leetcode#30]
`vector<TreeNode *> *v`, `vector<TreeNode *> *lv, *rv` 定义成指针并不是很有必要。

由于现代编译器有[**RVO（返回值优化）**](https://en.wikipedia.org/wiki/Return_value_optimization)机制，所以定义成非指针的vector，在效率上应该不会有任何劣化。

并且，你这么做的话，会导致内存泄露。即`v` `lv` `rv`这几个变量有内存分配，但当函数返回的时候，这些内存都**“失踪”**了。

**Comment by ziyeqinghan** [comment]
RVO（返回值优化）机制: 不会调用复制构造函数。
